const { PORT, GOOGLE_MAPS_BACKEND_API_KEY, GOOGLE_MAPS_FRONTEND_API_KEY, SITE_URL } = process.env;

export const env = {
  PORT: PORT ? Number(PORT) : 8080,
  GOOGLE_MAPS_BACKEND_API_KEY: GOOGLE_MAPS_BACKEND_API_KEY ?? "",
  GOOGLE_MAPS_FRONTEND_API_KEY: GOOGLE_MAPS_FRONTEND_API_KEY ?? "",
  SITE_URL: SITE_URL ?? "",
};
